# -*- coding: utf-8 -*-
"""pct2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVyrfyzfVy3MczMcoW6cqVS4fZ9Udho4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score
print("all set to go...")

df= pd.read_csv("/content/StudentsPerformance.csv")
df.columns= df.columns.str.lower().str.replace(" ","_")
df.sample(10)

df.drop(columns=["lunch"],inplace=True)

df['parental_level_of_education'].unique()

df.info()

df.shape

df.describe()

df.columns

for data_val in df.columns:
  print(df[data_val].value_counts())
  print("****"*5)

df.rename(columns=
          {"race/ethnicity":"race"},
          inplace=True)

sns.relplot(data=df,x="race",y="math_score",hue="gender",kind="scatter",row="gender")
plt.show()

df["race"].value_counts().plot(kind='pie',autopct="%.2f")

sns.displot(data=df, x="math_score",kind="kde",fill=True)

sns.displot(data=df,x="math_score",y="race",kind="hist",bins=20)

sns.violinplot(data=df, x='gender', y='math_score', hue='race', split=False)

df

sns.catplot(data=df,x="test_preparation_course",y='math_score',kind='box')

df.sample(5)

sns.displot(data=df, x="math_score",kde=True,kind='hist',color='green')

upper_limit = df['math_score'].mean()+3*df['math_score'].std()
lower_limit = df['math_score'].mean()-3*df['math_score'].std()
print(upper_limit)
print(lower_limit)

df[(df['math_score']>111.57824028802841) | (df['math_score']<20.599759711971593)]

df["math_score_z"]=(df['math_score']-df['math_score'].mean())/df["math_score"].std()
new_df= df[(df['math_score_z']<=3)& (df['math_score_z']>=-3)]
new_df

df['math_score'] = np.where(df['math_score']>upper_limit,upper_limit,
                            np.where(df['math_score']<lower_limit,lower_limit,df['math_score']))
df

def remove_outliers(dataframe,columns,threshold=3):
  df_copy=dataframe.copy()
  for cols in columns:
    mean = df_copy[cols].mean()
    std = df_copy[cols].std()

    z_score = f"{cols}_z"
    df_copy[z_score] = (df_copy[cols]-mean)/std

    df_copy = df_copy[(df_copy[z_score]<=threshold)& (df_copy[z_score]>=-threshold)]
    df_copy = df_copy.drop(columns=[z_score])


  return df_copy

col_remove = ['math_score','writing_score','reading_score']
new_df = remove_outliers(df,columns=col_remove)
new_df

plt.figure(figsize=(15,6))
plt.subplot(1,3,1)
sns.histplot(data=df, x="math_score",kde=True,)

plt.subplot(1,3,2)
sns.histplot(data=df, x="reading_score",kde=True)

plt.subplot(1,3,3)
sns.histplot(data=df, x="writing_score",kde=True)
plt.show()

x_train,x_test,y_train,y_test =train_test_split(df.drop(columns=['math_score','math_score_z'],axis=1),df['math_score'],test_size=0.2,random_state=2)

x_train

scaler = StandardScaler()
trf = ColumnTransformer([
    ("scaler",scaler,['reading_score','writing_score'])]
    ,remainder='passthrough',verbose_feature_names_out=False)
trf.set_output(transform='pandas')
x_train_trf=trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

x_train_trf

ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
trf2 = ColumnTransformer([
    ("ohe",ohe,['gender','race','parental_level_of_education',"test_preparation_course"])]
    ,remainder="passthrough",verbose_feature_names_out=False
)
trf2.set_output(transform="pandas")
x_train_trf=trf2.fit_transform(x_train_trf)
x_test_trf=trf2.transform(x_test_trf)

x_train_trf

models ={
 "LinearRegression": LinearRegression(),
"Decision Tree": DecisionTreeRegressor(random_state=42),
"Random Forest": RandomForestRegressor(random_state=42),
"KNN": KNeighborsRegressor(),
"SVR": SVR()
}

for name, model in models.items():
  model.fit(x_train_trf,y_train)
  y_pred = model.predict(x_test_trf)
  score= r2_score(y_test,y_pred)
  print(f"{name}: {score:.4f}")

